import turtle
scr = turtle.Screen()
scr.title("square")
scr.bgcolor("black")
scr.setup(800,800)
pen = turtle.Turtle()
pen.color("red")
pen.pensize(5)
pen.shape("turtle")
pen.fillcolor()
pen.begin_fill()
pen.penup()
pen.goto(-200,100)
pen.pendown()
for i in range(2):
    pen.fd(400)
    pen.rt(90)
    pen.fd(200)
    pen.rt(90)
pen.end_fill()
pen.hideturtle()
