import turtle
scr = turtle.screen()
scr.title("circle")
scr.bgcolor("black")
scr.setup(800,800)
pen = turtle.Turtle()
pen.color("golden")
pen.speed(5)
pen.pensize(5)
pen.shape("turtle")
pen.fillcolor()
pen.begin_fill()
pen.circle(30)
pen.end_fill()
pen.hideturtle()
